# Generated by Django 5.1.1 on 2024-09-25 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
